engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
exclude_paths:
  - config/
  - test/
  - public/
env:
  node: true
