language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  codeclimate:
    repo_token:a9c8fe57ddda9188ecee04bd020551fe5633ed1efc2552f37b96710f8957aeb3
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
